modal added
js-tasks-ru/htmlcss-20230411_dorovenco pull request #10
Opened 2023-04-27 07:46 UTC by DaniilDorovenko

2023-04-27 07:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-28 14:20 UTC, GSemikozov requested changes

2023-04-28 14:20 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.cross {
.modal__cross

2023-04-29 08:54 UTC, DaniilDorovenko commented on 05-lection3/02-modal/modal.css
> +.cross {
переименовал класс крестика

2023-05-12 14:30 UTC, GSemikozov requested changes

2023-05-12 14:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +	left: 480px;
а если ширина модалки будет 320px?
лучше right: 24px (или сколько там в макете)

2023-05-13 06:30 UTC, DaniilDorovenko commented on 05-lection3/02-modal/modal.css
> +	left: 480px;
исправил на отступ справа

2023-05-20 07:18 UTC, DaniilDorovenko commented on 05-lection3/02-modal/modal.css
> +	left: 480px;
Заменил икноку крестика на спрайт

2023-05-24 12:46 UTC, GSemikozov approved these changes

2023-05-24 12:46 UTC, merged