06 lection4 06 sprite
js-tasks-ru/htmlcss-20230411_dorovenco pull request #12
Opened 2023-05-05 12:23 UTC by DaniilDorovenko

Сверстал и добавил svg спрайт

2023-05-05 12:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-12 14:33 UTC, GSemikozov requested changes
мало создать спрайт - надо еще вставить иконки в уже готовые компоненты , где возможно)

2023-05-20 06:52 UTC, DaniilDorovenko commented
Добавил стрелку в аккордеон, в тултип и модалку добавлю в соответствующие ветки

2023-05-24 12:48 UTC, GSemikozov requested changes
конфликт

2023-05-26 21:55 UTC, GSemikozov approved these changes

2023-05-26 21:55 UTC, merged