Dz inner page grid
js-tasks-ru/htmlcss-20230411_dorovenco pull request #16
Opened 2023-05-09 12:49 UTC by DaniilDorovenko

2023-05-09 12:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-09 17:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-12 14:35 UTC, GSemikozov requested changes

2023-05-12 14:35 UTC, GSemikozov commented on pages/inner.css
> +h1, ul {
не нужно все стили страницы описывать в 1 файле. Здесь тот же принцип что и при верстке Главной: надо собирать страницу из блоков, соответственно пеериспользовать уже имеющиеся, и создавать новые

2023-05-22 08:29 UTC, DaniilDorovenko commented on pages/inner.css
> +h1, ul {
перенес слили внутренней в компоненты

2023-05-24 12:53 UTC, GSemikozov requested changes
конфликты

2023-05-24 12:53 UTC, GSemikozov commented on components/content/content.css
> +h1, ul {
глобальные стили ни в коем случае не описываем в компонентах (либо normalize, либо main)

2023-05-24 12:53 UTC, GSemikozov commented on components/content/content.css
> +.content__grid__sidebar {
.content_grid-container .content__sidebar

2023-05-24 12:53 UTC, GSemikozov commented on components/content/content.css
> +.content__grid-content {
.content__inner

2023-05-24 12:53 UTC, GSemikozov commented on components/content/content.css
> +.content__sidebar__title {
если здесь уже начинаем описывать элементы элемента (заголовок и айтемы сайдбара) - то это означает что сайдбар проще оформить как отдельный блок

2023-05-24 12:53 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title_inner {
.footer_inner .footer__title

2023-05-26 05:48 UTC, DaniilDorovenko commented on components/content/content.css
> +h1, ul {
перенес в normalize

2023-05-26 05:54 UTC, DaniilDorovenko commented on components/content/content.css
> +.content__grid__sidebar {
исправил

2023-05-26 05:55 UTC, DaniilDorovenko commented on components/content/content.css
> +.content__grid-content {
исправил

2023-05-26 05:57 UTC, DaniilDorovenko commented on components/footer/footer.css
> +.footer__title_inner {
исправил

2023-05-26 06:11 UTC, DaniilDorovenko commented on components/content/content.css
> +.content__sidebar__title {
пернес

2023-05-26 06:11 UTC, DaniilDorovenko commented on components/content/content.css
> +.content__grid__sidebar {
перенес все в отдельный блок

2023-05-26 21:56 UTC, GSemikozov requested changes
конфликт

2023-06-09 14:22 UTC, GSemikozov approved these changes

2023-06-09 14:22 UTC, merged