main page mobile
js-tasks-ru/htmlcss-20230411_dorovenco pull request #17
Opened 2023-05-12 12:18 UTC by DaniilDorovenko

2023-05-12 12:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-12 14:37 UTC, GSemikozov requested changes

2023-05-12 14:37 UTC, GSemikozov commented on components/card/card.css
> +    	display: flex;
дублировать свойства которые определены ранее и не меняются - не надо

2023-05-12 14:37 UTC, GSemikozov commented on components/card/card.css
> +    	display: flex;
актуально для всего ПР-а

2023-05-13 06:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-13 06:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-14 11:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-14 11:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-23 05:17 UTC, DaniilDorovenko commented on components/card/card.css
> +    	display: flex;
убрал дубли из карточек и футера

2023-05-24 12:54 UTC, GSemikozov requested changes
все ок, но - конфликты

2023-05-26 21:57 UTC, GSemikozov approved these changes

2023-05-26 21:57 UTC, merged