checkbox added
js-tasks-ru/htmlcss-20230411_dorovenco pull request #18
Opened 2023-05-19 08:25 UTC by DaniilDorovenko

2023-05-19 08:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-19 14:43 UTC, GSemikozov requested changes

2023-05-19 14:43 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +
display: inline-block; position: relative

2023-05-19 14:43 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	padding-bottom: 16px;
лишнее

2023-05-19 14:43 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	height: 27px;
точно ли иконке нужна такая высота

2023-05-19 14:43 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	fill: var(--white);
чтобы не менять цвет через fill, лучше в самой свг в fill прописать currentColor

2023-05-23 05:33 UTC, DaniilDorovenko commented on 07-lection5/01-checkbox/checkbox.css
> +
добавил

2023-05-23 05:33 UTC, DaniilDorovenko commented on 07-lection5/01-checkbox/checkbox.css
> +	padding-bottom: 16px;
убрал padding

2023-05-23 05:34 UTC, DaniilDorovenko commented on 07-lection5/01-checkbox/checkbox.css
> +	height: 27px;
с размерами не очень понятно, так как иконка не квадратная. Сделал поменьше...

2023-05-23 05:35 UTC, DaniilDorovenko commented on 07-lection5/01-checkbox/checkbox.css
> +	fill: var(--white);
если убрать fill белый, currentColor окрашивает иконку черный, что есть не совсем то что надо.

2023-05-24 12:55 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	fill: var(--white);
цвет при использовании currentColor меняем через свойство `color` вместо `fill`, в этом смысл)

2023-05-26 06:52 UTC, DaniilDorovenko commented on 07-lection5/01-checkbox/checkbox.css
> +	fill: var(--white);
понял, исправил

2023-05-26 21:58 UTC, GSemikozov requested changes
конфликт

2023-06-09 14:23 UTC, GSemikozov approved these changes

2023-06-09 14:23 UTC, merged