toggler added
js-tasks-ru/htmlcss-20230411_dorovenco pull request #20
Opened 2023-05-19 10:01 UTC by DaniilDorovenko

2023-05-19 10:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-24 12:57 UTC, GSemikozov requested changes

2023-05-24 12:57 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler {}
см ПР по радио

2023-05-24 12:57 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    fill: var(--grey-3);
см ПР по чекбоксу

2023-05-26 07:04 UTC, DaniilDorovenko commented on 07-lection5/03-toggler/toggler.css
> +.toggler {}
исправил

2023-05-26 07:04 UTC, DaniilDorovenko commented on 07-lection5/03-toggler/toggler.css
> +    fill: var(--grey-3);
исправил, все цвета svg

2023-05-26 21:58 UTC, GSemikozov approved these changes

2023-05-26 21:58 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-05-26 21:59 UTC, GSemikozov approved these changes

2023-05-26 21:59 UTC, merged