03 lection1 01 button
js-tasks-ru/htmlcss-20230411_dorovenco pull request #4
Opened 2023-04-20 07:36 UTC by DaniilDorovenko

2023-04-20 07:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-20 11:17 UTC, GSemikozov requested changes

2023-04-20 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
не хватает font-family

2023-04-20 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	color: #FFFFFF;
цвета сразу ставим из переменных

2023-04-20 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	color: #FFFFFF;
*такой цвет есть

2023-04-20 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	padding: 15px 61px;
высота точно будет соответствовать макету?)

2023-04-20 11:17 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_disabled
.button:disabled, отдельный класс не нужен

2023-04-20 11:17 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +    	<button class="button button_primary button_disabled">Primary</button>
вместо класса - атрибут disabled

2023-04-21 05:57 UTC, DaniilDorovenko commented on 03-lection1/01-button/button.css
> +
В макете шрифт Roboto, в верстке наследуется из main.css:
`* {
    font-family: 'Roboto', sans-serif;
}`
Все равно добавить в стили компонента?

2023-04-21 06:09 UTC, DaniilDorovenko commented on 03-lection1/01-button/button.css
> +	color: #FFFFFF;
Исправил

2023-04-21 06:09 UTC, DaniilDorovenko commented on 03-lection1/01-button/button.css
> +.button_disabled
Исправил

2023-04-21 06:09 UTC, DaniilDorovenko commented on 03-lection1/01-button/index.html
> +    	<button class="button button_primary button_disabled">Primary</button>
Исправил

2023-04-21 06:09 UTC, DaniilDorovenko commented on 03-lection1/01-button/button.css
> +	padding: 15px 61px;
Исправил

2023-04-21 20:02 UTC, GSemikozov requested changes

2023-04-21 20:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
у нас на проекте 3 разных шрифта, отнаследоваться можно от любого, поэтому - здесь точно лучше явно прописать (плюс задавать осн шрифт через `*` нельзя, вроде об этом рассказывал на примере с аккордионом)

2023-04-24 08:02 UTC, DaniilDorovenko commented on 03-lection1/01-button/button.css
> +
Добавил шрифт для .button

2023-04-25 12:39 UTC, GSemikozov approved these changes

2023-04-25 12:39 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-04-25 12:40 UTC, GSemikozov approved these changes

2023-04-25 12:40 UTC, merged