skeleton added
js-tasks-ru/htmlcss-20230411_dorovenco pull request #8
Opened 2023-04-26 10:12 UTC by DaniilDorovenko

2023-04-26 10:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-26 14:23 UTC, GSemikozov requested changes

2023-04-26 14:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__title {
.skeleton__title

2023-04-26 14:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.item_round {
.skeleton__item_round

2023-04-26 14:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.item_halfe {
.skeleton__item_halfe

2023-04-26 14:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.item_quarter {
.skeleton__item_quarter

2023-04-28 09:28 UTC, DaniilDorovenko commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__title {
изменил имя элемента

2023-04-28 09:29 UTC, DaniilDorovenko commented on 04-lection2/02-skeleton/skeleton.css
> +.item_round {
изменил имя модификатора

2023-04-28 09:30 UTC, DaniilDorovenko commented on 04-lection2/02-skeleton/skeleton.css
> +.item_halfe {
изменил имя модификатора

2023-04-28 09:30 UTC, DaniilDorovenko commented on 04-lection2/02-skeleton/skeleton.css
> +.item_quarter {
изменил имя модификатора

2023-04-28 14:18 UTC, GSemikozov approved these changes

2023-04-28 14:18 UTC, merged